GoodbyeWorldFunction:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: goodbye_world/
    Handler: app.lambda_handler
    Runtime: python3.8
    Events:
      GoodbyeWorld:
        Type: Api
        Properties:
          Path: /goodbye
          Method: get
#!inc resources/logg.yml GoodbyeWorldFunction
