---
HelloWorldFunction:
  Type: AWS::Serverless::Function
  Properties:
    CodeUri: hello_world/
    Handler: app.lambda_handler
    Runtime: python3.8
    Events:
      HelloWorld:
        Type: Api
        Properties:
          Path: /hello
          Method: get

HelloWorldFunctionLogGroup:
  Type: AWS::Logs::LogGroup
  DependsOn: HelloWorldFunction
  Properties:
    RetentionInDays: 7
    LogGroupName: !Join ["", ["/aws/lambda/", !Ref HelloWorldFunction]]
